%
%  GStudio Documentation: DataImport
%
%  Created by dyer on 2011-07-20.



\chapter{Parent Offspring Data}

\section{Synopsis}

There are several cases where you have data that consists of both adults and offspring.  With these kinds of data, there are some interesting kinds of analyses available for examining structure and diversity.  The functionality that \texttt{gstudio} provides focuses on translations of offspring data into common formats that can be analyzed using regular routines.


\section{Getting Data}

The use of GoogleDocs as a repository for your data is not unique to parent-offspring data and is used here to demonstrate how to utilize this options.  There is a more detailed discussion of how to set up your GoogleSpreadsheets so that you can access them in the \texttt{DataImport} vignette.  In what follows, I will use the \emph{Cornus florida} data.  I split URL (see Data Import) because it was so long it trailed off the page...  

<<>>=
require(gstudio)
data(cornus_florida)
cornus <- cornus_florida
@

The structure of adult/offspring data is just like any other kind of data and can consist of covariates such as physical location, size, etc. along with strata and loci.  The distinction is that there must be \emph{at least} two strata columns:
\begin{description}
	\item[Individual ID] There should a column in the dataset that has identification number or names that are unique to adults.  Every adult \emph{must} have a unique identification numver.
	\item[Offspring ID] To differentiate offspring from adults, the Offspring ID column should have the maternal individual (or paternal if you like) equal to 0.  Offspring from this individual have non-zero values for the Offspring ID column.  Offspring do not need to all have unique Offspring ID designations, just unique ones within the set of offspring with the same Individual ID.  
\end{description}

Here is an example to show the distinctions. 

<<>>=
family <- offspring.array(cornus,474)
family
@

Notice that all the offspring from mom '474' have the same IndID and she is differentiated from the offspring by having 'OffID=0'.  In fact, all the adults in the dataset can be found as:

<<>>=
adults <- cornus[cornus$OffID==0,]
adults
@


\section{Pollen Pools}

Since my research is primarily focused on the analysis of plant populations and mother/offspring combinations provide information about pollen donors, naturally these kinds of analyses will be the first kind to have functionality.

\subsection{Minus Mom}

If you have the collection of offspring and a mother, you can estimate pollen pool allele frequencies as by subtracting the maternal contribution to each genotype and then estimating the allele frequencies of the paternal components (this could be reversed if you have father/offspring data and need to estimate maternal genotype frequencies just as easily).

<<>>=
offs <- minus.mom( cornus )
offs
freqs.G8 <- Frequencies(offs$G8)
freqs.G8
@

Now the distinction should be made that these are the pollen donor allele frequencies since the contribution of the maternal individual has been removed from each offspring, the differences you can see as by comparing the above to:

<<>>=
unreduced.offs <- cornus[cornus$OffID!=0,]
freqs.unreduced.G8 <- Frequencies( unreduced.offs$G8 )
freqs.unreduced.G8
@

where the genotype of each offspring has 50\% of the mother's genotype.

\subsection{Genetic Distances and Structure (e.g., 2Gener)}

The reduced genotypes can be used in traditional genetic analyses as any other type of genetic data.  For example, the Two-Generation Analysis of Pollen Structure (hereafter 2Gener; Smouse \emph{et al.} 2001, Dyer \emph{et al.} 2004) is essentially an AMOVA analysis on pollen donor genotypes.  This is a bit of a manual version of it but it can be conducted as (in the next version I'll add a the AMOVA/2Gener options to the \texttt{genetic.structure} function).

<<>>=
require(pegas,quietly=TRUE,warn.conflicts=FALSE)
D <- genetic.distance(offs,mode="AMOVA")[[1]]
D <- as.dist(D)
Moms <- as.factor( offs$IndID )
amova(D ~ Moms)
@

\section{Paternity}

The \texttt{gstudio} package has some basic functionality regarding estimating paternity (or maternity if you have those kinds of data).  Thus far, only fractional paternity is implemented and only basically.  

Initially, 

<<>>=
pollen.freqs <- allele.frequencies( offs )
Pexcl <- lapply( pollen.freqs, exclusion.probability)
Pexcl
@

The multilocus exclusion probability is given by:

\[
P_{excl} = 1 - \prod_{i=1}^\ell(1-P_{excl,i})
\]

which in R can be found as:

<<>>=
1- prod((1-unlist(Pexcl)))
@


Which means that on average, these loci are expected to be able to exclude 98.6\% of potential fathers for an mother/offspring pair.  

The function \texttt{paternity} estimates fractional paternity for a particular mother and set of offspring.  Fractional paternity is estimated using multilocus Mendelian transition probabilities for triplet of male parent (MP), female parent (FP), and offspring (O) standardized by the likelihood of all potential fathers.   

\[
\lambda_i = \frac{T(O|FP,MP_i)}{\sum_{\forall k}T(O|FP,MP)_k}
\]

This ensures that $\sum \lambda = 1$.  The function \texttt{paternity} estimates this for all the offspring within a single family providing the subset of offspring that have potential fathers in the population, the identity of each father, and the fractional likelihood of each father.

<<>>=
pat <- paternity(cornus,474)
print(pat)
@


You can visualize the results using the \texttt{paternity.spiderplot} function that plots the location of all the individuals and indicates putative paternity by connecting mothers and indicated fathers.

<<label=spiderplot,fig=true,include=false>>=
paternity.spiderplot(cornus,pat,X="X",Y="Y", bty="n", xlab="X", ylab="Y")
@

\begin{figure}
	\centering
<<fig=T>>=
<<spiderplot>>
@
	\caption{Spatial pattern of parentage for family 474 in the \emph{Cornus florida} dataset.  Darkness of the lines indicated fractional paternity (light=less, darker=greater).}
\end{figure}


